### PR TITLE
Cleaned up the parametersets

### PR DESCRIPTION
**Pull request by MikeShepard**
don't need all of the duplicate information in the parameter attributes.
See
http://www.jonathanmedd.net/2013/01/add-a-parameter-to-multiple-parameter-sets-in-powershell.html

### CODE REVIEW

**Comment by RamblingCookieMonster** [comment]
Hi Mike!

I could be wrong, but I believe the attributes need to be specified for each parameter set.

For example, if you create a dummy Invoke-SqlCmdTest function:

```powershell
function Invoke-SqlCmdTest {
    [cmdletbinding(DefaultParameterSetName = 'Ins-Que')]
    param(
          [Parameter( ParameterSetName='Ins-Fil')]
          [Parameter( ParameterSetName='Ins-Que',
                        Position=0,
                        Mandatory=$true,
                        ValueFromPipeline=$true,
                        ValueFromPipelineByPropertyName=$true,
                        ValueFromRemainingArguments=$false)]
            [string[]]
            $ServerInstance,

            [Parameter( ParameterSetName='Ins-Fil')]
            $Test
    )

    process
    {
        foreach($SQLInstance in $ServerInstance)
        {
            "Testing $SQLInstance..."
        }
    }
}
```

Notice that if you try piping content to it in the Ins-Fil parameter set, it fails:

```powershell
1..3 | Invoke-SqlCmdTest -Test $True
```

```
Invoke-SqlCmdTest : The input object cannot be bound to any parameters for the command either because the command does not take pipeline input or the input and its properties 
do not match any of the parameters that take pipeline input.
```

It's quite ugly, but I think those parameter attributes need to stay, otherwise PowerShell assumes the default attribute values (e.g. no pipeline input)

Let me know if I'm missing something, just got out from a day of training, brain might be fried : )

Thanks!

Warren

**Comment by MikeShepard** [comment]
Hmmm,,,,I looked at the generated syntax for both functions (before and
after the change) and they were identical.  I'll play around a bit tonight
and see what's going on.

I do know I haven't ever seen other attributes repeated like that, which is
what led me to my update.

On Mon, Oct 26, 2015 at 4:10 PM, Warren F. <notifications@github.com> wrote:

> Hi Mike!
>
> I could be wrong, but I believe the attributes need to be specified for
> each parameter set.
>
> For example, if you create a dummy Invoke-SqlCmdTest function:
>
> function Invoke-SqlCmdTest {
>     [cmdletbinding(DefaultParameterSetName = 'Ins-Que')]
>     param(
>           [Parameter( ParameterSetName='Ins-Fil')]
>           [Parameter( ParameterSetName='Ins-Que',                        Position=0,                        Mandatory=$true,                        ValueFromPipeline=$true,                        ValueFromPipelineByPropertyName=$true,                        ValueFromRemainingArguments=$false)]
>             [string[]]
>             $ServerInstance,
>
>             [Parameter( ParameterSetName='Ins-Fil')]
>             $Test
>     )
>
>     process
>     {
>         foreach($SQLInstance in $ServerInstance)
>         {
>             "Testing $SQLInstance..."
>         }
>     }
> }
>
> Notice that if you try piping content to it in the Ins-Fil parameter set,
> it fails:
>
> 1..3 | Invoke-SqlCmdTest -Test $True
>
> Invoke-SqlCmdTest : The input object cannot be bound to any parameters for the command either because the command does not take pipeline input or the input and its properties
> do not match any of the parameters that take pipeline input.
>
> It's quite ugly, but I think those parameter attributes need to stay,
> otherwise PowerShell assumes the default attribute values (e.g. no pipeline
> input)
>
> Let me know if I'm missing something, just got out from a day of training,
> brain might be fried : )
>
> Thanks!
>
> Warren
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RamblingCookieMonster/PowerShell/pull/6#issuecomment-151285828>
> .
>



-- 
https://powershellstation.com

**Comment by MikeShepard** [comment]
Looks like you're right.  I guess I haven't ever had to specify the same
parameter in multiple parameter sets before.  The link I put in the note (
http://www.jonathanmedd.net/2013/01/add-a-parameter-to-multiple-parameter-sets-in-powershell.html)
doesn't repeat the options in the parameter attributes, but the only one
listed is Mandatory=$false, which is default.

By the way, I'm curious about including Position= attributes and things
like ValueFromRemainingArguments=$false which is understood. Is there a
specific reason for including these? I've actually made an effort to remove
them from SQLPSX since they just seem like noise.

On Mon, Oct 26, 2015 at 4:10 PM, Warren F. <notifications@github.com> wrote:

> Hi Mike!
>
> I could be wrong, but I believe the attributes need to be specified for
> each parameter set.
>
> For example, if you create a dummy Invoke-SqlCmdTest function:
>
> function Invoke-SqlCmdTest {
>     [cmdletbinding(DefaultParameterSetName = 'Ins-Que')]
>     param(
>           [Parameter( ParameterSetName='Ins-Fil')]
>           [Parameter( ParameterSetName='Ins-Que',                        Position=0,                        Mandatory=$true,                        ValueFromPipeline=$true,                        ValueFromPipelineByPropertyName=$true,                        ValueFromRemainingArguments=$false)]
>             [string[]]
>             $ServerInstance,
>
>             [Parameter( ParameterSetName='Ins-Fil')]
>             $Test
>     )
>
>     process
>     {
>         foreach($SQLInstance in $ServerInstance)
>         {
>             "Testing $SQLInstance..."
>         }
>     }
> }
>
> Notice that if you try piping content to it in the Ins-Fil parameter set,
> it fails:
>
> 1..3 | Invoke-SqlCmdTest -Test $True
>
> Invoke-SqlCmdTest : The input object cannot be bound to any parameters for the command either because the command does not take pipeline input or the input and its properties
> do not match any of the parameters that take pipeline input.
>
> It's quite ugly, but I think those parameter attributes need to stay,
> otherwise PowerShell assumes the default attribute values (e.g. no pipeline
> input)
>
> Let me know if I'm missing something, just got out from a day of training,
> brain might be fried : )
>
> Thanks!
>
> Warren
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RamblingCookieMonster/PowerShell/pull/6#issuecomment-151285828>
> .
>



-- 
https://powershellstation.com

**Comment by RamblingCookieMonster** [comment]
Hi Mike!

Yeah, tweaking this function helped me learn a bit about parameter sets : )

Completely agree - some of the attributes are remnants from the original function, sometimes updated without thought when new parameters were added.

Cheers!

**Pull request closed without merging**
